version: '3.8'
services:
  cassandra:
      image: cassandra:latest
      container_name: etl_cassandra_container
      ports:
        - "9042:9042"
      environment:
        - CASSANDRA_USER=cassandra
        - CASSANDRA_PASSWORD=DeJRwlKfIDjo
      restart: no
      volumes:
        - ./out/cassandra_data:/var/lib/cassandra
